### ISSUE TITLE
Icon to make cleaner

### ISSUE THREAD

**Issue by yieldhog** [theOrakle/glentronics#1]
Hi -- awesome integration, thank you! Any chance you could add an icon to make it a little cleaner? Not sure if the attached conforms to requirements for HA, but, good starting point.
![logo](https://github.com/theOrakle/glentronics/assets/3329021/1d12af8b-3bf0-4b80-b945-b84493ea8883)

**Comment by theOrakle** [comment]
I'm not a graphics guy, but if you want to contribute, see this [link](https://developers.home-assistant.io/blog/2020/05/08/logos-custom-integrations/)

The domain name is glentronics, once you get the images published, they will show for everyone...

**Comment by yieldhog** [comment]
Cool, thanks. I’m not a graphics person either but will give it a shot. Integration is great.
